"use client";

import React from "react";

export default function Footer() {
  return (
    <footer className="w-full border-t border-slate-900 bg-slate-950 py-4 text-xs text-slate-500">
      <div className="max-w-5xl mx-auto px-4 sm:px-6 flex items-center justify-between">
        <p>Generated by Wayfarer AI</p>
        <p>© {new Date().getFullYear()}</p>
      </div>
    </footer>
  );
}
